package code.essence.display.screens.clickgui.components.implement.module;

import code.essence.features.impl.render.jumpCircle.receiver.JumpCircleModule;
import code.essence.features.module.Module;
import code.essence.features.impl.combat.*;
import code.essence.features.impl.misc.*;
import code.essence.features.impl.movement.*;
import code.essence.features.impl.player.*;
import code.essence.features.impl.render.*;

public class ModuleDescriptions {
    public static String getDescription(Module module) {
        if (module instanceof Particles) return "Отображает частицы в мире";
        if (module instanceof TargetStrafe) return "Преследует цель во время атаки";
        if (module instanceof Strafe) return "Позволяет стрейфиться";
        
        if (module instanceof AirStuck) return "Позволяет зависнуть в воздухе";
        if (module instanceof ElytraMotion) return "Замирает на элитрах возле противника";
        if (module instanceof HighJump) return "Подбрасывает вас вверх";
        if (module instanceof ShiftTap) return "Автоматически приседает при ударе";
        if (module instanceof AspectRatio) return "Изменяет соотношение сторон экрана";
        if (module instanceof FreeLook) return "Позволяет свободно вращать камеру";
        if (module instanceof ClickPearl) return "Автоматически бросает эндер жемчуг при нажатии бинда";
        if (module instanceof ClickFriend) return "Добавляет игроков в список друзей при нажатии бинда";
        if (module instanceof WindJump) return "Использует заряд ветра по бинду";
        if (module instanceof TargetESP) return "Подсвечивает противника";
        if (module instanceof NoWeb) return "Убирает замедление при движении через паутину";
        if (module instanceof ServerHelper) return "Предоставляет полезные функции для игры на серверах";
        if (module instanceof ItemScroller) return "Уменьшает заддержку на складирование предметов";
        if (module instanceof Hud) return "Отображает дополнительную информацию на экране";
        if (module instanceof ClickGui) return "Настраивает внешний вид и поведение ClickGui";
        if (module instanceof AuctionHelper) return "Помогает на аукционе";
        if (module instanceof Prediction) return "Предсказывает траекторию полета снарядов";
        if (module instanceof XRay) return "Позволяет видеть сквозь блоки для поиска руд";
        if (module instanceof Aura) return "Автоматически атакует противника";
        if (module instanceof AutoSwap) return "Позволяет менять предметы во второй руке по бинду";
        if (module instanceof NoFriendDamage) return "Не дает ударить друзей";
        if (module instanceof HitBoxModule) return "Изменяет размер хитбоксов сущностей";
        if (module instanceof AntiBot) return "Обнаруживает и игнорирует ботов на сервере";
        if (module instanceof AutoExplosion) return "Автоматически размещает и взрывает кристаллы";
        if (module instanceof AutoSprint) return "Автоматически включает спринт при движении";
        if (module instanceof NoPush) return "Отключает отталкивание";
        if (module instanceof ElytraHelper) return "Помощник для действий с элитрами";
        if (module instanceof ServerJoiner) return "Автоматически подключается к серверу";
        if (module instanceof NoDelay) return "Убирает задержки при выполнении действий";
        if (module instanceof Velocity) return "Уменьшает отбрасывание персонажа";
        if (module instanceof AutoRespawn) return "Автоматически возрождает игрока после смерти";
        if (module instanceof NoSlow) return "Убирает замедление при использовании предметов";
        if (module instanceof GuiMove) return "Позволяет двигаться при открытом интерфейсе";
        if (module instanceof Blink) return "Замедляет отправку пакетов на сервер";
        if (module instanceof AutoTool) return "Автоматически выбирает подходящий инструмент для добычи";
        if (module instanceof Fly) return "Позволяет летать";
        if (module instanceof FastBreak) return "Ускоряет разрушение блоков";
        if (module instanceof CameraSettings) return "Настраивает камеру игрока";
        if (module instanceof Speed) return "Увеличивает скорость передвижения игрока";
        if (module instanceof SwingAnimation) return "Настраивает анимацию взмаха руки";
        if (module instanceof ViewModel) return "Изменяет отображение позиции предметов в руке";
        if (module instanceof BlockOverlay) return "Подсвечивает блоки для лучшей видимости";
        if (module instanceof ElytraGlide) return "Позволяет плавно скользить при движении";
        if (module instanceof Esp) return "Показывает сущностей через стены";
        if (module instanceof NameTags) return "Отображает информацию о сущности над её головой";
        if (module instanceof ShulkerView) return "Позволяет видеть содержимое шалкер-боксов";
        if (module instanceof BlockESP) return "Подсвечивает определенные блоки";
        if (module instanceof AutoTotem) return "Автоматически использует тотемы бессмертия";
        if (module instanceof EnderChestPlus) return "Расширяет функционал эндер-сундука";
        if (module instanceof FreeCam) return "Предоставляет инструменты для свободной камеры";
        if (module instanceof ChestStealer) return "Быстро забирает предметы из контейнеров";
        if (module instanceof AutoTpAccept) return "Автоматически принимает запросы на телепортацию";
        if (module instanceof AutoAuth) return "Автоматически вводит пароль/регистрируется для авторизации";
        if (module instanceof Arrows) return "Отображает стрелочки на сущностей";
        if (module instanceof AutoLeave) return "Автоматически покидает сервер при угрозе";
        if (module instanceof WorldTweaks) return "Настраивает параметры мира";
        if (module instanceof NoClip) return "Позволяет проходить сквозь блоки";
        if (module instanceof NoRender) return "Отключает отображение определенных объектов";
        if (module instanceof NameProtect) return "Скрывает имена игроков для защиты";
        if (module instanceof SeeInvisible) return "Позволяет видеть невидимых игроков";
        if (module instanceof AutoArmor) return "Автоматически надевает лучшую броню";
        if (module instanceof AutoUse) return "Автоматически использует предметы";
        if (module instanceof NoInteract) return "Блокирует взаимодействие с объектами";
        if (module instanceof CrossHair) return "Настраивает отображение прицела";
        if (module instanceof SuperFireWork) return "Усиливает действие фейерверка для полета";
        if (module instanceof Spider) return "Позволяет ползать по стенам как паук";
        if (module instanceof SafeWalk) return "Предотвращает падение с краев блоков";
        if (module instanceof ServerRPSpoofer) return "Подделывает данные ресурс-пака для серверов";
        if (module instanceof NoFall) return "Предотвращает получение урона от падения";
        if (module instanceof DeathCoords) return "Сохраняет координаты места смерти";
        if (module instanceof XCarry) return "Позволяет хранить предметы в слотах для крафта";
        if (module instanceof AntiAFK) return "Предотвращает кик за бездействие";
        if (module instanceof FakePing) return "Изменяет отображаемый пинг";
        if (module instanceof LevitationControl) return "Контролирует эффект левитации";
        if (module instanceof KillEffect) return "Добавляет визуальные эффекты при убийстве";
        if (module instanceof UseTracker) return "Отслеживает использование предметов";
        if (module instanceof ShulkerBypass) return "Позволяет доставать вещи из шалкер-боксов находясь в пвп";
        if (module instanceof AutoBuy) return "Автоматически покупает предметы на аукционе";
        if (module instanceof ChinaHat) return "Добавляет отображение китайской шляпы";
        if (module instanceof ElytraAura) return "Преследует противника во время полета на элитрах";
        if (module instanceof Criticals) return "Бьет критическими ударами там, где это невозможно (Паутина)";
        if (module instanceof JumpCircleModule) return "Добавляет отображение круга при прыжке";
        if (module instanceof AutoDodge) return "Автоматически уклоняется от снарядов";
        if (module instanceof ClientSounds) return "Настраивает звуки клиента";
        return "Описание модуля отсутствует";
    }
}